### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by codez** [lowjoel/activerecord-userstamp#5]
The current gem version is locked down to activerecord ~> 4.2. Will there be support for Rails 5?

**Comment by lowjoel** [comment]
I haven't tested that, do the specs work with Rails 5? I think it should though.

**Comment by codez** [comment]
I haven't tested neither.

**Comment by lowjoel** [comment]
Is it particularly urgent? Otherwise I'd just adopt a wait-and-see approach, especially since Rails 5 isn't out yet.

I'd also happily accept PRs :) Though I think we might need some work to get it tested with multiple Rails versions.

**Comment by paneer-tikka** [comment]
Rails 5 is out now. I've tried using this gem in my rails 5 project with [some modifications](https://github.com/paneer-tikka/activerecord-userstamp/commit/948e188cbc6f8f3f58746afbe705b60fd40edff1). 
_Disclaimer_ - The above commit is just a monkey-patch I was willing to live with until someone wiser does it the right way :).
The only problem I have noticed is that during development rails server fails to hot-reload when I update code (say some controller). It fails to reload code in rails server for the next request  with an exception like this:
`NoMethodError (undefined method`stamper=' for nil:NilClass):

/Users/foo/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/activerecord-userstamp-e656bdd1c380/lib/active_record/userstamp/controller_additions.rb:41:in `reset_stamper'
/Users/foo/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/activerecord-userstamp-e656bdd1c380/lib/active_record/userstamp/controller_additions.rb:24:in`ensure in with_stamper'
/Users/foo/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/activerecord-userstamp-e656bdd1c380/lib/active_record/userstamp/controller_additions.rb:24:in `with_stamper'
`

Re-starting rails server fixes this (presumably because the stamper class is now set correctly.

Any suggestions on how I might fix this issue? Also, any plans to make it rails 5 compatible?
